import re

def generator_numbers(text: str):
    """
    Generator that yields all real numbers from text.
    
    Numbers are clearly separated by spaces on both sides.
    """

    # Find all numbers as strings
    numbers = re.findall(r'(?<= )\d+\.?\d*(?= )', text)

    # Yield each number as float (generator!)
    for num in numbers:
        yield float(num)
    

def sum_profit(text: str, func: callable) -> callable:
    """
    Calculate sum of numbers generated by func.
    
    Args:
        text: Input text to analyze
        func: Generator function that yields numbers
        
    Returns:
        float: Sum of all numbers
    """
    return sum(func(text))
    

text = "Загальний дохід працівника складається з декількох частин: 1000.01 як основний дохід, доповнений додатковими надходженнями 27.45 і 324.00 доларів."

total_income = sum_profit(text, generator_numbers)
print(f"Загальний дохід: {total_income}")